server:
  port: 9090

spring:
  h2:
    console: 
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://host.docker.internal:19621/test_db
    username: test_user
    password: test123
logging:
  level:
    root: debug